### ISSUE TITLE
'setFeatureWeight' not defined for prog

### ISSUE THREAD

**Issue by LargePanda** [TeamCohen/TensorLog#1]
> AttributeError: 'ProPPRProgram' object has no attribute 'setFeatureWeight'

when running 
`ti.prog.setFeatureWeight('weighted',1,ti.db.ones())`

from: https://github.com/TeamCohen/TensorLog/wiki

**Comment by krivard** [comment]
Ah, that directive is for the dev branch. I've updated the wiki accordingly.
