### ISSUE TITLE
Are predicate negations supported?

### ISSUE THREAD

**Issue by mlpacheco** [TeamCohen/TensorLog#11]
I have been going through the paper, documentation and examples and I can't seem to find any reference to predicate negations. Is this currently supported?

For example, a simple use case of a program to avoid cycles when inferring edges:

directed_path(a,b) <= inferred_edge(a,b)
directed_path(a,c) <= directed_path(a,b) & directed_path(b,c)
not(directed_path(a,a))

**Comment by wwcohen** [comment]
No

**Comment by mlpacheco** [comment]
Thanks.
