### ISSUE TITLE
update `test-dir` to `test-data` run interactively

### ISSUE THREAD

**Issue by tigerneil** [TeamCohen/TensorLog#8]
In the wiki, we need to change 
`python -i -m tensorlog.interp --prog test-dir/textcat.ppr --proppr --db test-dir/textcattoy.cfacts` 
to 
`python -i -m tensorlog.interp --prog test-data/textcat.ppr --proppr --db test-data/textcattoy.cfacts`

seems `test-dir` already becomes `test-data` in source code. The wiki is outdated.

**Comment by tomsmoker** [comment]
This is done.  GitHub doesn't play nice with Wiki's, branches and PR's so I edited it directly. Apologies for the lack of communication.
